### ISSUE TITLE
Limit to element_composition 

### ISSUE THREAD

**Issue by hoelzerC** [grimme-lab/MindlessGen#63]
Allow limiting the output _only_ to elements denoted in `element_composition`. 

Some Options
1. Extra Flag `fix_element_composition`
2. Allow for `forbidden_elements = "1-*"` hack, i.e. forbid everything and overrule by `element_composition`. Currently raising a `ValueError` due to an empty multiprocess pool.
3. Set this option per default.

Current workaround:
Manually forbid all elements that are not within your choice of `element_composition` (inconvenient).

**Comment by marcelmbn** [comment]
Thanks for the feedback! 
The `forbidden_elements = "1-*"` "hack" should work and thus, this is also partially a bug. Other than that, also a "fix_element_composition" flag or similar might be useful.

**Comment by marcelmbn** [comment]
Let's implement this feature, as it would also simplify the access to isomers (-> if `fix_element_composition` is true, we would get isomers only anyway). Brought up by @gasevic.

### Points to consider
- Charge should not be set randomly, because for true structural isomers, we don't want IP/EA comparisons but only structural differences
- For the special case, that people want isomers but randomized charges, we can still implement a flag (`--random-charges`) with which people can turn the random charge assignment on and off and maybe optionally give a preference for closed-shell and open-shell cases (e.g., 0 and 1 (IMHO most default ones))
